In [1]:
import pandas as pd

In [2]:
url_tipos_seguro = "https://raw.githubusercontent.com/BAcost26/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

df = pd.read_csv(url_tipos_seguro)

df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [3]:
# Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [4]:
# Limpieza de datos
tipos_seguro = df.copy()

tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

for col in tipos_seguro.select_dtypes(include='object').columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)
tipos_seguro = tipos_seguro.replace("nan", pd.NA)

# Estandarizar categoria
tipos_seguro['categoria'] = tipos_seguro['categoria'].replace({
    'empresarial': 'Empresarial',
    'familiar': 'Familiar',
    'personal': 'Personal',
    'especial': 'Especial'
})

# Convertir valores inválidos de riesgo_base a nulos
tipos_seguro['riesgo_base'] = tipos_seguro['riesgo_base'].replace('-', pd.NA)

# Convertir riesgo_base a numérico
tipos_seguro['riesgo_base'] = pd.to_numeric(tipos_seguro['riesgo_base'], errors='coerce')

# Eliminar duplicados
tipos_seguro = tipos_seguro.drop_duplicates()

tipos_seguro.head()

   id_tipo_seguro        tipo    categoria  riesgo_base
0               1        Pyme     Familiar          NaN
1               2  Industrial  Empresarial         4.68
2               3  Industrial     Familiar         5.10
3               4  Industrial     Personal          NaN
4               5        Auto  Empresarial         9.07

In [5]:
#Verificar nombres reales de columnas
print(tipos_seguro.columns)

Index(['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base'], dtype='object')

In [6]:
#Separar válidos y rechazados
validos = tipos_seguro[
    tipos_seguro['tipo'].notna() &
    tipos_seguro['categoria'].notna() &
    tipos_seguro['riesgo_base'].notna()
].copy()

rechazados = tipos_seguro[
    tipos_seguro['tipo'].isna() |
    tipos_seguro['categoria'].isna() |
    tipos_seguro['riesgo_base'].isna()
].copy()

In [7]:
def motivo(row):
    motivos = []

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacia")

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_base_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
print("\n✅ Válidos:")
print(validos)
print("\n❌ Rechazados con motivos:")
print(rechazados[['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base', 'motivo_rechazo']])

✅ Válidos:
    id_tipo_seguro        tipo    categoria  riesgo_base
1                2  Industrial  Empresarial         4.68
2                3  Industrial     Familiar         5.10
4                5        Auto  Empresarial         9.07
5                6  Industrial  Empresarial         2.52
6                7       Salud     Personal         0.92
7                8   Educación  Empresarial         7.42
9               10      Dental     Especial         2.70
10              11        Auto  Empresarial         4.33

❌ Rechazados con motivos:
    id_tipo_seguro        tipo categoria  riesgo_base  \
0                1        Pyme  Familiar          NaN
3                4  Industrial  Personal          NaN
8                9  Accidentes      <NA>         5.68
11              12    Agrícola      <NA>          NaN

                       motivo_rechazo
0                   riesgo_base_vacio
3                   riesgo_base_vacio
8                     categoria_vacia
11  categoria_vacia,riesgo_base_vacio

In [9]:
validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

In [10]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 64.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [11]:
from sqlalchemy import create_engine, text
import pandas as pd

database_url = "postgresql://etl_user:Zw56jAa5y6Zhp5hioIDelHMyHx8wrAmj@dpg-d6qu8qc50q8c73bpfi40-a.oregon-postgres.render.com/etl_seguros_xmv0"

engine = create_engine(database_url)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
    conn.commit()

print("Conexión exitosa")

Conexión exitosa

In [12]:
sql_create_curated = """
CREATE TABLE IF NOT EXISTS tipos_seguro_curated (
    id_tipo_seguro INT PRIMARY KEY,
    tipo VARCHAR(100),
    categoria VARCHAR(100),
    riesgo_base FLOAT
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_curated))
    conn.commit()

print("Tabla tipos_seguro_curated creada")

Tabla tipos_seguro_curated creada

In [13]:
sql_create_rejects = """
CREATE TABLE IF NOT EXISTS tipos_seguro_rejects (
    id_tipo_seguro INT,
    tipo VARCHAR(100),
    categoria VARCHAR(100),
    riesgo_base FLOAT,
    motivo_rechazo VARCHAR(200)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_rejects))
    conn.commit()

print("Tabla tipos_seguro_rejects creada")

Tabla tipos_seguro_rejects creada

In [14]:
validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

print("Datos cargados correctamente")

Datos cargados correctamente

In [15]:
pd.read_sql("SELECT * FROM tipos_seguro_curated LIMIT 10", engine)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               2  Industrial  Empresarial         4.68
1               3  Industrial     Familiar         5.10
2               5        Auto  Empresarial         9.07
3               6  Industrial  Empresarial         2.52
4               7       Salud     Personal         0.92
5               8   Educación  Empresarial         7.42
6              10      Dental     Especial         2.70
7              11        Auto  Empresarial         4.33

In [16]:
pd.read_sql("SELECT * FROM tipos_seguro_rejects LIMIT 10", engine)

,id_tipo_seguro,tipo,categoria,riesgo_base,motivo_rechazo
0,1,Pyme,Familiar,NaN,riesgo_base_vacio
1,4,Industrial,Personal,NaN,riesgo_base_vacio
2,9,Accidentes,None,5.68,categoria_vacia
3,12,Agrícola,None,NaN,"categoria_vacia,riesgo_base_vacio"